tap "aylei/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jenkins-x/jx"
tap "jzaleski/jzaleski"
tap "universal-ctags/universal-ctags"
brew "python"
brew "aws-shell"
brew "awscli"
brew "bash"
brew "bat"
brew "cfssl"
brew "coreutils"
brew "fasd"
brew "fd"
brew "fzf"
brew "gawk"
brew "gnu-getopt"
brew "gnu-sed"
brew "htop"
brew "httpie"
brew "hub"
brew "icdiff"
brew "ipcalc"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "kubernetes-helm"
brew "kubespy"
brew "lf"
brew "lftp"
brew "mas"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "node@10"
brew "pass"
brew "pipenv"
brew "ponysay"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "ripgrep"
brew "shellcheck"
brew "sops"
brew "speedtest-cli"
brew "stern"
brew "telnet"
brew "terminal-notifier"
brew "terraform"
brew "tig"
brew "tmux"
brew "unrar"
brew "vim"
brew "watch"
brew "wget"
brew "yadm"
brew "yq"
brew "zsh"
brew "aylei/tap/kubectl-debug"
brew "jenkins-x/jx/jx"
brew "jzaleski/jzaleski/apg"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD", "with-jansson"]
cask "1password"
cask "appcleaner"
cask "bartender"
cask "bettertouchtool"
cask "bitbar"
cask "blue-jeans"
cask "clipy"
cask "dash"
cask "docker-edge"
cask "fantastical"
cask "fluor"
cask "google-chrome"
cask "gpg-suite"
cask "grammarly"
cask "insomnia"
cask "iterm2"
cask "java"
cask "karabiner-elements"
cask "little-snitch"
cask "macvim"
cask "michaelvillar-timer"
cask "micro-snitch"
cask "microsoft-remote-desktop-beta"
cask "nordvpn"
cask "onyx"
cask "protonvpn"
cask "slack"
cask "spotify"
cask "teamviewer"
cask "telegram"
cask "touchswitcher"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "visualvm"
cask "vlc"
cask "wraparound"
cask "zoomus"
mas "1Blocker", id: 1107421413
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "CatchMouse", id: 439700005
mas "Gestimer", id: 990588172
mas "GoodTask", id: 1143437985
mas "Grammarly for Safari", id: 1462114288
mas "HazeOver", id: 430798174
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "Marked 2", id: 890031187
mas "Moom", id: 419330170
mas "PiPifier", id: 1160374471
mas "Pixelmator", id: 407963104
mas "PopClip", id: 445189367
mas "Reeder", id: 1449412482
mas "Roofs", id: 1449570266
mas "RSS Button for Safari", id: 1437501942
mas "The Archive Browser", id: 510232205
