alias c='zz'
alias cat='bat -np --paging=never --theme base16'
alias g='git'
alias k='kubectl'
alias htop='sudo htop'
alias ls='ls --color=auto'
alias rg='rg -i'
alias kctx='kubectx'
alias kns='kubens'
